apiVersion: apps/v1
kind: Deployment
metadata:
  name: matnani-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: matnani-api
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CLOUD_AWS_S3_CDN_URL
              value: https://d2l9pqrf1yjvvh.cloudfront.net/images
            - name: APP_CORS_ALLOWED_ORIGINS
              value: "https://d2l9pqrf1yjvvh.cloudfront.net,https://matnani.store"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
