apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matnani-app-secret
  namespace: team3-matnani-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: team3-matnani-prod-secret-store
    kind: ClusterSecretStore
  target:
    name: matnani-app-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /team3/matnani/prod/db-url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /team3/matnani/prod/db-username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /team3/matnani/prod/db-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: /team3/matnani/prod/jwt-secret
    - secretKey: SPRING_DATA_REDIS_HOST
      remoteRef:
        key: /team3/matnani/prod/redis-host
    - secretKey: BUSINESS_API_KEY
      remoteRef:
        key: /team3/matnani/prod/business-api-key
    - secretKey: CLOUD_AWS_S3_BUCKET
      remoteRef:
        key: /team3/matnani/prod/s3-bucket-name
