apiVersion: apps/v1
kind: Deployment
metadata:
  name: matnani-api
  labels:
    app: matnani-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matnani-api
  template:
    metadata:
      labels:
        app: matnani-api
    spec:
      serviceAccountName: matnani-api
      containers:
        - name: matnani-api
          image: team3-matnani-api:latest
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: matnani-app-secret
          env:
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: CLOUD_AWS_REGION
              value: ap-northeast-2
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
