apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team3-matnani-dev-monitoring  # ArgoCD 대시보드에서 보이는 이름
  namespace: argocd               # ArgoCD 자체가 실행되는 네임스페이스
spec:
  project: team3-matnani-project

  # 어디서 가져올건지
  source:
    repoURL: 'https://github.com/CLD-05/team3-matnani-config.git'
    targetRevision: main
    path: monitoring/overlays/dev

  # 배포 대상(EKS 클러스터)
  destination:
    server: 'https://kubernetes.default.svc'   # 현재 EKS 클러스터 (내부 주소)
    namespace: monitoring                      # 이 네임스페이스에 배포

  # 자동화 정책 (GitOps의 핵심)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
