apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team3-matnani-app-prod
  namespace: argocd
spec:
  project: team3-matnani-project
  source:
    repoURL: 'https://github.com/CLD-05/team3-matnani-config.git'
    targetRevision: main
    path: apps/team3-matnani/overlays/prod

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: team3-matnani-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true