apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: externalsecret-patch.yaml
    target:
      kind: ExternalSecret
      name: slack-webhook
  - path: alertmanagerconfig-patch.yaml
    target:
      kind: AlertmanagerConfig
      name: slack-config
  - path: servicemonitor-patch.yaml
    target:
      kind: ServiceMonitor
      name: matnani-api
